### ISSUE TITLE
MATLAB R2018a compatibility issue

### ISSUE THREAD

**Issue by araue** [Data2Dynamics/d2d#111]
Hi all,

It seems like they changed the way to create symbolic expression. 
We use `sym(str)` everywhere in the code.
This produces an error in 2018a, recommended it to use the function str2sym now.

Need to find a way to fix this while keeping backward compatibility to older MATLAB versions...

Andreas

**Comment by rengesser** [comment]
One possibility is to create a new function, e.g. `myStr2Sym(str,matlabVersion)`, which calls, depending on the Matlab version, ` sym(str)` or `str2sym(str)` and replace all `sym(str)` with the new function.

**Comment by clemenskreutz** [comment]
I already started ...
Just wait some minutes :-)

**Comment by clemenskreutz** [comment]
Replacing everythin as suggested by rengesser was not an issue.
The major problem is that R2018a does not accept symbolic terms with [], e.g. sym('x[1]').

**Comment by clemenskreutz** [comment]
The above mentioned issue might be solved e.g. be the replacement regexprep(str,'\[(\d+)\]','__$1__') forth and back. However, another issue occured which seems like a matlab bug:

%%  R2016: tmp and tmp2 are the same
tmp = sym('[a,b]') % creating a sympolic array/matrix
char(tmp)
tmp2 = sym(char(tmp)) % conversion to character and back to sym

%%  R2018a: tmp and tmp2 are NOT the same
tmp = str2sym('[a,b]')  % creating a sympolic array/matrix
char(tmp)
tmp2 = str2sym(char(tmp))

**Comment by JoepVanlier** [comment]
Not a solution to the main problem, but it might be worth comparing the regexp solution to two separate string replacements in terms of performance. I remember switching out a whole bunch of regexps earlier because regexprep was considerably slower than strrep. I know that in some cases regexp is a lot safer, but in this case we could just use a large recognized string _LEFT_BRACKET_ or something.

I read that the syntax for sym2str is different from the syntax for sym, so it might have something to do with that. Whereas sym(#) used to take mupad input, sym2str takes MATLAB input.

My guess is that char still outputs mupad stuff. So I guess the conversion we are looking for is mupad => matlab.
https://de.mathworks.com/help/symbolic/differences-between-matlab-and-mupad-syntax.html

**Comment by why-fi** [comment]
Hi! Are there any new developments on this issue?

**Comment by timmaiwald** [comment]
Added custom casting function "arMyStr2Sym(#)" according to the discussion above. I've tested a few of the examples and all compiled without error in Matlab 2018a. Closing issue for now, please re-open if there are still problems with it.
