### ISSUE TITLE
distributionPlot:  Plot not smooth enough

### ISSUE THREAD

**Issue by brianpenghe** [Data2Dynamics/d2d#127]
Is there a way to reduce the bin size? The figure doesn't look smooth enough.

<img width="580" alt="screen shot 2018-07-11 at 1 10 39 pm" src="https://user-images.githubusercontent.com/4110443/42596893-fbd3b99c-850b-11e8-98bf-bbce0b6c30f5.png">

**Comment by brianpenghe** [comment]
The setting I used was 'variableWidth',true,'globalNorm',3,'histOpt',1.1,'color','b','distWidth',1,'divFactor',0.5

**Comment by hhass** [comment]
Hi Brian,

the script for distributionPlot is not part of the D2D framework, but was only added to the npjSysBio example in order to generate some of the plots.
The original functionality was uploaded to the MATLAB File Exchange (https://de.mathworks.com/matlabcentral/fileexchange/23661-violin-plots-for-plotting-multiple-distributions-distributionplot-m).

As far as i understand the help of the function, playing around with the inputs for histOpt and divFactor might result in the desired smoothness. Maybe histOpt 1 or 2 with a larger divFactor will help. Or you choose histOpt = 0, with a large divFactor which represents the number of bins. But this may hamper the readability of your plot and produce non-desired kinks.

Cheers
Helge

**Comment by brianpenghe** [comment]
I played with larger divFactors but they didn't help when histopt is set at 1.1 .

**Comment by hhass** [comment]
DistributionPlot is not part of d2d, please refer to matlab file exchange and the author of the package.
