### ISSUE TITLE
using nonlinear constrain in fmincon

### ISSUE THREAD

**Issue by arnabbandyopadhyay** [Data2Dynamics/d2d#156]
Hi, 

I want to use nonlinear constrain for estimating parameters and i want to use fmincon. In arFit.m file I see I can pass constrain function: myconfun = @confun,  but it is not straight forward to me how do I write this constrain function and how do I pass this into fitting. can you please guide me how to resolve this, or if there are other ways I can pass nonlinear constrains in to he fitting.  I appreciate your help.
Thanks
Arnab

**Comment by clemenskreutz** [comment]
Hi. Nonlinear optimization with constraints is difficult. Often, optimization does not converge because the constraints cannot be justified. Penalized optimization is much more robust. You can increase the penality strength iteratively apply "increasing the penalization strength" & optimization. Penalties can be integrated via parameters (see ar.type) or via new observables (without data). If you nevertheless decide to perform constrained optimization, you have to also provide the correct derivatives of the constraints (w.r.t. parameters). Constraint violation and its derivative are output arguments of @ConFun. The implementation is like in standard fmincon examples (see "Nonlinear Constraints" chapter in the Matlab help)
