### ISSUE TITLE
running simulation with different initial condition without compiling

### ISSUE THREAD

**Issue by arnabbandyopadhyay** [Data2Dynamics/d2d#157]
Hi D2D team,
I want to check the dynamics starting from different initial conditions keeping parameters, observables same. What I want to implement is the following:

arInit
arLoadModel(deffile);
arLoadData(datafile);
arCompileAll;

for i=1:100
   modify initial condition
   arFitLHS
   arPlot
   store data
end

computation time is very high if I compile inside the for loop. Which variable do I need to modify for changing initial condition, or is there other way to implement this?

Thank you

**Comment by adrianhauber** [comment]
Hi arnabbandyopadhyay,

if you do not specify the initial condition of an observable in the CONDITIONS section in the data or model def file, D2D will interpret the initial condition as a parameter that can be estimated alongside the other parameters of your model. To set it to a fixed value, you may use `arSetPars` with the `qFit` argument set to zero instead of "modify initial condition" in the pseudocode you provided. 

Best, 
Adrian
