### ISSUE TITLE
ODE Parameter Estimation

### ISSUE THREAD

**Issue by iliailmer** [Data2Dynamics/d2d#171]
Hi, I had a question about using d2d for estimation of initial conditions and parameters from an ODE system with outputs.

I have a small ODE such as
```
d/dt(r) = k1 * r - k2 * r * w,
d/dt(w) = k2 * r * w - k3 * w
```
and the output sample from the following functions
```
y1 = r+w
y2 = w
```

How can I convert this model into d2d-accepted format for estimation? Is there a tutorial/example on how to do that? 
Thanks!

**Comment by clemenskreutz** [comment]
Our Wiki https://github.com/Data2Dynamics/d2d/wiki provides a lot of documentation and examples. 

Model definition is described at this page: https://github.com/Data2Dynamics/d2d/wiki/Setting%20up%20models

Many example models are in the folder "arFramework3/Examples".

A few short hints: 
Use arCreateProject to get almost empty standard templates for the model definition file and adapt this.
You need 2 STATES (use more then one letter, e.g. rState instead of r), parameters for initial conditions are automatically created and two OBSERVABLES. 
You don't need an INPUTS, all STATES are in one COMPARTMENT.
