### ISSUE TITLE
ar.chi2err

### ISSUE THREAD

**Issue by leshaker** [Data2Dynamics/d2d#42]
Originally reported by: **Vimalathithan Devaraj (Bitbucket: [dvimal27](https://bitbucket.org/dvimal27), GitHub: Unknown)**

---

Dear Sir,

Could you please tell me how ar.chi2err is computed and why does it's always negative

Thank you in advance

With regards,
Vimal

---
- Bitbucket: https://bitbucket.org/d2d-development/d2d-software/issue/42

**Comment by JoanneJansen** [comment]
Hi!

I am not sure if this will be read/if this is the right place to ask, as this question was asked years ago, but I thought I would give it a try.

I wondered why ar.chi2err is always zero when you do not estimate errors? I.e.: why is it [-2 log(L) = 2ar.ndatalog(sqrt(2pi)) + x^2/sigma^2] and not [-2 log(L) = 2ar.ndatalog(sqrt(2pi)) + 2log(sigma) +x^2/sigma^2]? Shouldn't this term be included in the log-likelihood regardless of whether experimental errors are used?

Thanks in advance,

Best, Jo

**Comment by JoepVanlier** [comment]
> Hi!
> 
> I am not sure if this will be read/if this is the right place to ask, as this question was asked years ago, but I thought I would give it a try.
> 
> I wondered why ar.chi2err is always zero when you do not estimate errors? I.e.: why is it [-2 log(L) = 2ar.ndatalog(sqrt(2pi)) + x^2/sigma^2] and not [-2 log(L) = 2ar.ndatalog(sqrt(2pi)) + 2log(sigma) +x^2/sigma^2]? Shouldn't this term be included in the log-likelihood regardless of whether experimental errors are used?
> 
> Thanks in advance,
> 
> Best, Jo

This field is not used when you don't fit errors. While you are right, that the -2 log(L) would contain a term for the normalizing constant, this error term is fixed and its omission does not change the location of the minimum. Hence it is not computed. You raise a valid point though, it should really not be reported as -2 log(L) in such a case, since that's not what is being returned, merely something proportional to -2 log(L).

**Comment by JoanneJansen** [comment]
Okay, thanks for the quick reply!
