### ISSUE TITLE
Likelihood in plot not updated during fitting (ar.config.showFitting=1)

### ISSUE THREAD

**Issue by mschilling10** [Data2Dynamics/d2d#85]
If ar.config.useNewPlots=1 and ar.config.showFitting=1, the likelihood that is written in the plot of the observation functions is not updated after each iteration. This is working if ar.config.useNewPlots=0. It would be nice if somebody could fix this as I need this feature for teaching purposes.

**Comment by JoepVanlier** [comment]
I've committed a temporary hotfix for this, which forces a 'slow' redraw of the plot when useNewPlots is set to 1 and a fitting animation is requested. This means that this will result in slower plotting than when using the old plots however. The problem here is that arPlot2 doesn't update the text labels and doesn't store them (so it's not that easily fixed).

**Comment by JoepVanlier** [comment]
Forced slower plotting when using fitting animation and the new plots.
