### ISSUE TITLE
Initialisation of sensitivities for parameters not influencing the steady state

### ISSUE THREAD

**Issue by JanHasenauer** [Data2Dynamics/d2d#97]
I'm currently studying a new model with multiple experimental conditions. All conditions start from the same steady state. Then I execute arSteadyState, I get the message:

```
Warning: Certain parameters in target condition not present in steady state reference! 
> In arSteadyState (line 195) 
Warning: The following sensitivities will *not* take the equilibration into account: 
> In arSteadyState (line 196) 
k_deg_PGI2
```

This is not surprising as the parameter k_deg_PGI2 does indeed not influence the steady state. I was however wondering now with which value the sensitivity with respect to the parameter is initialised. It should be zero but I did not find this information.

It might be a good idea to add it.

**Comment by JoepVanlier** [comment]
Hi Jan,

thanks for the report. For these sensitivities nothing was carried over. They were considered as though they were completely independent. For a degradation parameter, this would mean the initial value for the sensitivity is indeed zero (as you would expect). But for example, an initial condition that is set specifically for a condition might have a non-zero initial sensitivity.

This behaviour was not correct however. Such a sensitivity should only be non-zero if the state was not carried over, since the initial would immediately be overwritten by the steady state. The sensitivity is now correctly set to zero in all cases in the last commit.

Thanks for bringing this to my attention! :)

**Comment by JanHasenauer** [comment]
Dear Joep,
thanks a lot for the quick feedback! This answers all my questions.
-- Jan

**Comment by JoepVanlier** [comment]
Dear Jan,

Glad to help! Closing the issue.

Best,
  Joep.
